app:
  name: "Golang Viper"
  version: "1.0.0"
database:
  mysql:
    host: "localhost"
    port: 3306
    username: "localhost"
    password: "12345678"
  postgres:
    host: "localhost"
    port: 5432
    username: "postgres"
    password: "postgres"
email:
  host: "smtp.gmail.com"
  port: 587
  username: "mail@gmail.com"
  password: "password"
