CREATE TABLE IF NOT EXISTS correct (
    id    INT           NOT NULL AUTO_INCREMENT,
    name  VARCHAR(255)  NOT NULL,
    PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS wrong (
    id    INT           NOT NULL AUTO_INCREMENT,
    name  VARCHAR(255)  NOT NULL,
    PRIMARY KEY (id)
) ENGINE = InnoDB;
